<?php 
	$imagesDir = 'panel/';
	$panels = array(
			/*array(
				'prodID' 	=> '',
				'title' 	=> '',
				'selo'      => '',//images size 105 x 105
				'logoSrc' 	=> '',//images size 175px X 135px
				'tamanho' 	=> '',
				'desc'		=> '<span class="destaqueDescricao"></span>',
				'endereco'	=> '',
				'mapa'		=> '',
				'link'		=> '',
				'slider' 	=> array(//images size 550px X 292px
						array('title'=>'','src'=>''),
						array('title'=>'','src'=>''),
						array('title'=>'','src'=>''),
					),
			),*/
			array(
				'page'      => 'jacarepagua',
				'nome'		=> 'BELA VISTA',
				'prodID' 	=> '52',
				'emailProdID' 	=> '92',
				'title' 	=> 'JACAREPAGUÁ',
				'selo'      => 'obras-avancadas.png',
				'logoSrc' 	=> 'logo_Jacarepagua.png',
				'tamanho' 	=> '<strong>2</strong> e <strong>3</strong> quartos',
				'desc'		=> 'com varanda e amplo lazer.<span class="destaqueDescricao"> More ao lado da futura Transolímpica. Últimas unidades!</span>',
				'endereco' 	=> 'Estrada do Boiúna, 1600 - Taquara',
				'mapa'		=> 'https://maps.google.com.br/maps?q=Estrada+do+Boi%C3%BAna,+1600+-+Taquara&ie=UTF8&hnear=Estr.+Boi%C3%BAna,+1600+-+Taquara,+Rio+de+Janeiro,+22723-021&t=m&z=16',
				'link'		=> 'http://cury.net/rj/belavistajacarepagua?utm_source=sitefeiraorj&utm_medium=botaoinfo&utm_campaign=feiraorj',
				'slider' 	=> array( //images size 550px X 292px
						array('title'=>'','src'=>'Jaca-BelaVistaBOIUNA_PE_CHURRASQUEIRA_2011_09_06.jpg'),
						array('title'=>'','src'=>'Jaca-BelaVistaBOIUNA_PE_FACHADA1_2011_09_06.jpg'),
						array('title'=>'','src'=>'Jaca-BelaVistaBOIUNA_PE_FESTAS_2011_09_06.jpg'),
						array('title'=>'','src'=>'Jaca-BelaVistaBOIUNA_PE_PISCINA_2011_09_06.jpg'),
						array('title'=>'','src'=>'Jaca-BelaVistaBOIUNA_PE_PLAYGROUND_2011_09_06.jpg'),
					),
			),
			array(
				'page'      => 'rocha-miranda',
				'nome'		=> 'DEZ',
				'prodID' 	=> '67',
				'emailProdID' 	=> '116',
				'title' 	=> 'ROCHA MIRANDA',
				'selo'      => 'selo-transparent.fw.png',
				'logoSrc' 	=> 'logo_Rocha_Miranda.png',//images size 175px X 135px
				'tamanho' 	=> '<strong>2</strong> quartos',
				'desc'		=> 'com varanda e amplo lazer. <span class="destaqueDescricao">Próximo ao Parque Madureira. Play com piscina e churrasqueira.</span>',
				'endereco'	=> 'Estrada do Barro Vermelho, 484 - Rocha Miranda',
				'mapa'		=> 'http://maps.google.com.br/maps?q=Estrada+do+Barro+Vermelho,+484,+Rocha+Miranda,+Rio+de+Janeiro&hl=pt&sll=-22.066441,-42.924029&sspn=4.351859,8.453979&oq=Estrada+do+Barro+Vermelho,+484+-+Rocha+Miranda&hnear=Estr.+do+Barro+Vermelho,+484+-+Rocha+Miranda,+Rio+de+Janeiro,+21540-500&t=m&z=17',
				'link'		=> 'http://cury.net/rj/DezRochaMiranda?utm_source=sitefeiraorj&utm_medium=botaoinfo&utm_campaign=feiraorj',
				'slider' 	=> array(//images size 550px X 292px
						array('title'=>'','src'=>'RochaMiranda-DEZ-BARRO_VERMELHO_AP01_03_AGO(Large).jpg'),
						array('title'=>'','src'=>'RochaMiranda-DEZ-BRINQUEDOTECA(Large).jpg'),
						array('title'=>'','src'=>'RochaMiranda-DEZ-PLAYGROUN(Large).jpg'),
						array('title'=>'','src'=>'RochaMiranda-DEZ-SALA_GINASTICA(Large).jpg'),
						array('title'=>'','src'=>'RochaMiranda-DEZ-SALAO_JOGOS(Large).jpg'),
					),
			),
			array(
				'page'      => 'sao-goncalo',
				'nome'		=> 'COMPLETO SÃO GONÇALO',
				'prodID' 	=> '64',
				'emailProdID' 	=> '121',
				'title' 	=> 'SÃO GONÇALO',
				'selo'      => 'obras-iniciadas.png',
				'logoSrc' 	=> 'logo_Sao_Goncalo.png',//images size 175px X 135px
				'tamanho' 	=> '<strong>2</strong> quartos',
				'desc'		=> 'com vaga e amplo lazer. <span class="destaqueDescricao">Primeira fase 100% vendida. Piscinas, fitness e churrasqueira.</span>',
				'endereco'	=> 'Rua Vicente de Lima Cleto, 451 - Nova Cidade',
				'mapa'		=> 'http://maps.google.com.br/maps?q=Rua+Vicente+de+Lima+Cleto,+451+-+Nova+Cidade&hl=pt&ie=UTF8&sll=-22.805297,-43.02516&sspn=0.008456,0.016512&hnear=R.+Vicente+Lima+Cleto,+451+-+Nova+Cidade,+S%C3%A3o+Gon%C3%A7alo+-+Rio+de+Janeiro,+24455-000&t=m&z=17&iwloc=A',
				'link'		=> 'http://cury.net/rj/CompletoSaoGoncalo2?utm_source=sitefeiraorj&utm_medium=botaoinfo&utm_campaign=feiraorj',
				'slider' 	=> array(//images size 550px X 292px
						array('title'=>'','src'=>'SaoGoncalo-guarita(Large).jpg'),
						array('title'=>'','src'=>'SaoGoncaloPiscina(Large).jpg'),
						array('title'=>'','src'=>'SaoGoncalo-play(Large).jpg'),
						array('title'=>'','src'=>'SaoGoncalo-quadra(Large).jpg'),
						array('title'=>'','src'=>'SaoGoncalo-Salao_de_Festas(Large).jpg'),
					),
			),
			array(
				'page'      => 'pavuna',
				'nome'		=> 'ESTAÇÃO ZONA NORTE',
				'prodID' 	=> '90',
				'emailProdID' 	=> '97',
				'title' 	=> 'PAVUNA',
				'selo'      => 'obras-avancadas.png',
				'logoSrc' 	=> 'logo-Estacao_Zona_Norte.png',//images size 175px X 135px
				'tamanho' 	=> '<strong>2</strong> e <strong>3</strong> quartos',
				'desc'		=> 'com vaga e amplo lazer. <span class="destaqueDescricao">A 400 m do metrô Pavuna. Clube com 3 mil m2 de diversão.</span>',
				'endereco'	=> 'Rua Brás Cubas x Rua Capitão Gouveia - Pavuna',
				'mapa'		=> 'http://maps.google.com.br/maps?q=Rua+Br%C3%A1s+Cubas,+rua+Capit%C3%A3o+Gouveia+-+Pavuna&hl=pt&ie=UTF8&sll=-22.809364,-43.364422&sspn=0.008456,0.016512&hq=Rua+Br%C3%A1s+Cubas,&hnear=R.+Cap.+Gouveia+-+Pavuna,+Rio+de+Janeiro,+21520-030&t=m&z=17',
				'link'		=> 'http://www.cury.net/estacaozonanorte?utm_source=sitefeiraorj&utm_medium=botaoinfo&utm_campaign=feiraorj',
				'slider' 	=> array(//images size 550px X 292px
						array('title'=>'','src'=>'PAVUNA_PE_CHURRASQUEIRA_2011_06_07(Large).jpg'),
						array('title'=>'','src'=>'PAVUNA_PE_FESTAS-CLUBE_2011_06_07(Large).jpg'),
						array('title'=>'','src'=>'PAVUNA_PE_GERAL-CLUBE_2011_06_07(Large).jpg'),
						array('title'=>'','src'=>'PAVUNA_PE_PISCINA_2011_06_07(Large).jpg'),
						array('title'=>'','src'=>'PAVUNA_PE_QUADRA_2011_06_07(Large).jpg'),
					),
			),
			array(
				'page'      => 'engenho-novo',
				'nome'		=> 'MÉRITO',
				'prodID' 	=> '76',
				'emailProdID' 	=> '122',
				'title' 	=> 'ENGENHO NOVO',
				'selo'      => 'selo-transparent.fw.png',
				'logoSrc' 	=> 'logo_Engenho_Novo.png',//images size 175px X 135px
				'tamanho' 	=> '<strong>2</strong> e <strong>3</strong> quartos',
				'desc'		=> 'com varanda e vaga de garagem. <span class="destaqueDescricao">Fácil acesso ao Centro, Zona Norte e Jacarepaguá. Lazer com piscinas e churrasqueira.</span>',
				'endereco'	=> 'Rua Leopoldino Bastos, 44 - Engenho Novo',
				'mapa'		=> 'http://maps.google.com.br/maps?q=Rua+Leopoldino+Bastos,+44+-+Engenho+Novo&hl=pt&ie=UTF8&sll=-22.809364,-43.364422&sspn=0.008456,0.016512&hnear=R.+Leopoldino+Bastos,+44+-+Graja%C3%BA,+Rio+de+Janeiro,+20715-200&t=m&z=17&iwloc=A',
				'link'		=> 'http://cury.net/rj/meritoengenhonovo?utm_source=sitefeiraorj&utm_medium=botaoinfo&utm_campaign=feiraorj',
				'slider' 	=> array(//images size 550px X 292px
						array('title'=>'','src'=>'EngenhoNovo-Cury_LEOPOLDINO_01_FACHADA.jpg'),
						array('title'=>'','src'=>'EngenhoNovo-CURY_LEOPOLDINO_03_SALAO_DE_FESTAS(Large).jpg'),
						array('title'=>'','src'=>'EngenhoNovo-CURY_LEOPOLDINO_05_PISCINA(Large).jpg'),
						array('title'=>'','src'=>'EngenhoNovo-CURY_LEOPOLDINO_06_CHURRASQUEIRA(Large).jpg'),
						array('title'=>'','src'=>'EngenhoNovo-CURY_LEOPOLDINO_07_PLAYGROUND(Large).jpg'),
					),
			),
			array(
				'page'      => 'tomas-coelho',
				'nome'		=> 'COMPLETO ZONA NORTE',
				'prodID' 	=> '68',
				'emailProdID' 	=> '117',
				'title' 	=> 'TOMÁS COELHO',
				'selo'      => 'selo-transparent.fw.png',
				'logoSrc' 	=> 'logo_Zona_Norte.png',
				'tamanho' 	=> '<strong>2</strong> quartos',
				'desc'		=> 'com vaga e amplo lazer. <span class="destaqueDescricao">Em frente ao metrô e próximo do Norte Shopping. Play com piscinas adulto e infantil.</span>',
				'endereco'	=> 'Rua Moacyr de Almeida, 611 - Tomás Coelho',
				'mapa'		=> 'http://maps.google.com.br/maps?q=Rua+Moacyr+de+Almeida,+611+-+Tom%C3%A1s+Coelho&hl=pt&ie=UTF8&sll=-22.913094,-43.266141&sspn=0.008449,0.016512&hnear=R.+Moacyr+de+Almeida,+611+-+Tom%C3%A1s+Coelho,+Rio+de+Janeiro,+20750-340&t=m&z=17&iwloc=A',
				'link'		=> 'http://www.cury.net/rj/completozonanorte?utm_source=sitefeiraorj&utm_medium=botaoinfo&utm_campaign=feiraorj',
				'slider' 	=> array(//images size 550px X 292px
						array('title'=>'','src'=>'TomasCoelho-CompletoZN-CHURRASQUEIRA(Large).jpg'),
						array('title'=>'','src'=>'TomasCoelho-CompletoZN-FACHADA_FUNDOS(Large).jpg'),
						array('title'=>'','src'=>'TomasCoelho-CompletoZN_PISCINA(Large).jpg'),
						array('title'=>'','src'=>'TomasCoelho-CompletoZN-PLAYGROUND(Large).jpg'),
						array('title'=>'','src'=>'TomasCoelho-CompletoZN-SALAO_DE_FESTAS_ITAOCARA.jpg'),
					),
			),
			array(
				'page'      => 'campo-grande',
				'nome'		=> 'SUPERA',
				'prodID' 	=> '51',
				'emailProdID' 	=> '77',
				'title' 	=> 'CAMPO GRANDE',
				'selo'      => 'pronto-pra-morar.png',
				'logoSrc' 	=> 'logo_Campo_Grande.png',//images size 175px X 135px
				'tamanho' 	=> '<strong>2</strong> e <strong>3</strong> quartos',
				'desc'		=> 'com varanda e lazer completo. <span class="destaqueDescricao">No melhor ponto da Cachamorra e fácil acesso à Barra. Pronto para morar!</span>',
				'endereco'	=> 'Estrada da Cachamorra, 1.115 - Campo Grande',
				'mapa'		=> 'http://maps.google.com.br/maps?q=Estrada+da+Cachamorra,+1.115+-+Campo+Grande&hl=pt&sll=-22.066441,-42.924029&sspn=4.351859,8.453979&hnear=Estr.+da+Cachamorra,+1115+-+Campo+Grande,+Rio+de+Janeiro,+23040-150&t=m&z=17&iwloc=A',
				'link'		=> 'http://www.cury.net/rj/SuperaCampoGrande?utm_source=sitefeiraorj&utm_medium=botaoinfo&utm_campaign=feiraorj',
				'slider' 	=> array(//images size 550px X 292px
						array('title'=>'','src'=>'CpoGrande-Supera-CACHAMORRA_PE_CHURRASQUEIRA_2010_10_18.png'),
						array('title'=>'','src'=>'CpoGrande-Supera-CACHAMORRA_PE_FACHADA01_2010_10_18.jpg'),
						array('title'=>'','src'=>'CpoGrande-Supera-CACHAMORRA_PE_FESTAS_2010_10_19.jpg'),
						array('title'=>'','src'=>'CpoGrande-Supera-CACHAMORRA_PE_PLAY_2010_10_18.jpg'),
						array('title'=>'','src'=>'CpoGrande-Supera-CACHAMORRA_PE_RUAINTERNA_2010_10_18.jpg'),
					),
			),
		);
